### ISSUE TITLE
LUA SCRIPT and engine tutorials

### ISSUE THREAD

**Issue by Manu614** [TheZoroForce240/FNF-Extra-Keys-V2#11]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?
lua scripting support and tutorials in the future?

**Comment by TheZoroForce240** [comment]
Probably won't be adding lua scripts (lua has issues with high frame rates), and hscript is far more powerful than lua,
there's already a few guides on the wiki, though i never finished all of them, I may do some video tutorials in the future idk, I don't really get much time to work on this engine anymore.

**Comment by Manu614** [comment]
personally I think that this script is superior to lua in the field of power because with this script you can do something similar to itg but on the other hand lua can be a very good alternative for fast jobs that do not use too much space (although the space issue is irrelevant because now all computers can run almost everything without problems)

**Comment by Manu614** [comment]
and another thing is that my poor programming knowledge is focused on lua but I guess they won't add lua so I will start learning haxe lol
