### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by nintendofan44** [TheZoroForce240/FNF-Extra-Keys-V2#2]
## What is your suggestion, and why should it be implemented?
-----------------------------------------------------------------------------------
I suggest that you make this extra keys mod but for psych engine (latest version btw (0.4.2(main branch) https://github.com/ShadowMario/FNF-PsychEngine

**Comment by prokube** [comment]
https://github.com/TheZoroForce240/FNF-PsychEngine-EK-Port stubid
