### ISSUE TITLE
How to add custom characters and songs?

### ISSUE THREAD

**Issue by PedroGamer121** [TheZoroForce240/FNF-Extra-Keys-V2#4]
when i added a song and tried to play it, the game crashed 
The same thing happens when I take my custom character and put it in any song, the game crashes as soon as I go back to music.

**Comment by TheZoroForce240** [comment]
for adding songs, you probably misspelt or used a space in the name (haven't added support for spaces yet), misspelling the song name in freeplaysonglist.txt usually crashes the game. (also make sure theres no ke offset file in the chart folder, that usually makes half the charts not appear)

for custom characters, i have no idea what you might have done to break it, showing something like a pic of the folder and the json file might help me tell you whats wrong with it,
I suggest reading the wiki for custom characters if you haven't already

**Comment by PedroGamer121** [comment]
New question: how to add weeks and modcharts?
